config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: "account", path_names: {
    sign_up: "signup",
    sign_in: "signin",
    sign_out: "signout"
  }

  namespace :account do
    get "/", to: redirect("/account/settings/edit")
    get "/settings", to: redirect("/account/settings/edit")
    resource :settings, only: %i[edit update]
    resource :billing, only: :show
    resources :charges, only: :create
  end

  resources :pictures, param: :token, path: "p" do
    resource :lightbox, only: %i[show], module: :pictures
    resource :disabled, only: %i[create destroy], module: :pictures
    resource :featured, only: %i[create destroy], module: :pictures
    resource :like, only: %i[create destroy], module: :pictures

    collection do
      get "import"
      get "search"
    end
  end

  get "/u", to: redirect("/explore")
  resources :users, param: :username, path: "u", only: %i[show edit update] do
    member do
      put "follow"
      put "unfollow"
      get "followers"
      get "followees"
    end

    resources :albums, only: :index
    resources :pictures, only: :index
  end

  get "/a", to: redirect("/explore")
  resources :albums, param: :token, except: :index, path: "a" do
    resources :pictures, only: :index
  end

  namespace :admin do
    get "/", to: redirect("/admin/users")
    resources :billings, only: :index
    resources :users, only: :index
    resources :pictures, only: :index
    resources :invitations, param: :token, only: :index do
      member do
        put "approve"
      end
    end
  end

  resources :invitations, only: %i[new create]

  get "explore" => "explore#index"
  get "contact" => "about#contact"
  get "pricing" => "about#pricing"
  get "privacy" => "about#privacy"
  get "terms" => "about#terms"
  get "rules" => "about#rules"

  devise_scope :user do
    authenticated :user do
      root "timeline#index", as: :authenticated_root
    end

    unauthenticated do
      root "welcome#index"
    end
  end
end

app/views/admin/_nav.html.erb
<ul class="nav nav-pills flex-column mb-3">
  <% if Rails.configuration.invitation_enabled %>
    <li class="nav-item">
      <%= link_to 'Invitations', admin_invitations_path, class: "nav-link #{'active' if body_class == 'admin-invitations-index'}" %>
    </li>
  <% end %>
  <li class="nav-item">
    <%= link_to 'Users', admin_users_path, class: "nav-link #{'active' if body_class == 'admin-users-index'}" %>
  </li>
  <li class="nav-item">
    <%= link_to 'Pictures', admin_pictures_path, class: "nav-link #{'active' if body_class == 'admin-pictures-index'}" %>
  </li>
  <% if Rails.configuration.payment_enabled %>
    <li class="nav-item">
      <%= link_to 'Billings', admin_billings_path, class: "nav-link #{'active' if body_class == 'admin-billings-index'}" %>
    </li>
  <% end %>
</ul>