config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: "account", path_names: {
    sign_up: "signup",
    sign_in: "signin",
    sign_out: "signout"
  }

  namespace :account do
    get "/", to: redirect("/account/settings/edit")
    get "/settings", to: redirect("/account/settings/edit")
    resource :settings, only: %i[edit update]
    resource :billing, only: :show
    resources :charges, only: :create
  end

  resources :pictures, param: :token, path: "p" do
    resource :lightbox, only: %i[show], module: :pictures
    resource :disabled, only: %i[create destroy], module: :pictures
    resource :featured, only: %i[create destroy], module: :pictures
    resource :like, only: %i[create destroy], module: :pictures

    collection do
      get "import"
      get "search"
    end
  end

  get "/u", to: redirect("/explore")
  resources :users, param: :username, path: "u", only: %i[show edit update] do
    member do
      put "follow"
      put "unfollow"
      get "followers"
      get "followees"
    end

    resources :albums, only: :index
    resources :pictures, only: :index
  end

  get "/a", to: redirect("/explore")
  resources :albums, param: :token, except: :index, path: "a" do
    resources :pictures, only: :index
  end

  namespace :admin do
    get "/", to: redirect("/admin/users")
    resources :billings, only: :index
    resources :users, only: :index
    resources :pictures, only: :index
    resources :invitations, param: :token, only: :index do
      member do
        put "approve"
      end
    end
  end

  resources :invitations, only: %i[new create]

  get "explore" => "explore#index"
  get "contact" => "about#contact"
  get "pricing" => "about#pricing"
  get "privacy" => "about#privacy"
  get "terms" => "about#terms"
  get "rules" => "about#rules"

  devise_scope :user do
    authenticated :user do
      root "timeline#index", as: :authenticated_root
    end

    unauthenticated do
      root "welcome#index"
    end
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                      :integer          not null, primary key
#  email                   :string           default(""), not null
#  encrypted_password      :string           default(""), not null
#  reset_password_token    :string
#  reset_password_sent_at  :datetime
#  remember_created_at     :datetime
#  sign_in_count           :integer          default(0), not null
#  current_sign_in_at      :datetime
#  last_sign_in_at         :datetime
#  current_sign_in_ip      :inet
#  last_sign_in_ip         :inet
#  created_at              :datetime         not null
#  updated_at              :datetime         not null
#  username                :string
#  balance                 :integer          default(0), not null
#  fullname                :string
#  default_license         :string           default("CC BY-NC-ND"), not null
#  avatar                  :integer
#  avatar_filename         :string
#  customer_id             :string
#  followers_count         :integer          default(0)
#  followees_count         :integer          default(0)
#  default_privacy_setting :integer
#  role                    :integer          default("member")
#  locale                  :string
#  description             :text
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessor :invitation_token

  USERNAME_PATTERN = "[0-9A-Za-z][0-9A-Za-z-]{1,30}[0-9A-Za-z]".freeze
  FULLNAME_LENGTH_MAX = 50
  DESCRIPTION_LENGTH_MAX = 500

  acts_as_voter

  mount_uploader :avatar, AvatarUploader

  has_many :albums
  has_many :pictures

  has_many :follower_relationships, foreign_key: :followee_id, class_name: "Follow"
  has_many :followee_relationships, foreign_key: :follower_id, class_name: "Follow"
  has_many :followers, through: :follower_relationships, source: :follower
  has_many :followees, through: :followee_relationships, source: :followee

  after_initialize do
    self.locale ||= I18n.locale
  end

  before_create do
    self.balance = 1.gigabyte
  end

  enum role: %i[member moderator admin]

  enum default_privacy_setting: %i[public protected private], _suffix: :setting

  def self.locales
    {
      ar: "العربية",
      de: "Deutsch",
      en: "English",
      es: "Español",
      fr: "Français",
      ja: "日本語",
      pt: "Português",
      ru: "Русский"
    }.freeze
  end

  def self.default_licenses
    [
      "CC BY",
      "CC BY-SA",
      "CC BY-NC",
      "CC BY-ND",
      "CC BY-NC-SA",
      "CC BY-NC-ND"
    ].freeze
  end

  validates :locale, inclusion: { in: locales.keys.map(&:to_s) }
  validates :default_license, inclusion: { in: default_licenses }
  validates :email, presence: true, uniqueness: true
  validates :username, presence: true, uniqueness: true, format: /\A#{USERNAME_PATTERN}\z/
  validates :fullname, length: { maximum: FULLNAME_LENGTH_MAX }
  validates :description, length: { maximum: DESCRIPTION_LENGTH_MAX }
  validate :invitation_token_must_be_valid, on: :create, unless: :skip_invitation?

  def remember_me
    true
  end

  def to_param
    username
  end

  def name
    fullname.presence || username
  end

  def skip_invitation?
    admin? || !Rails.configuration.invitation_enabled
  end

  def invitation_token_must_be_valid
    approved_invitation = Invitation.approved.where(email: email, token: invitation_token)
    errors.add(:invitation_token, "is invalid") unless approved_invitation.exists?
  end

  def usage
    pictures.map(&:image).map(&:size).sum
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminController
  def index
    @users = User.order(created_at: :desc)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include PaginationContext

  respond_to :html, :json, :js, :atom

  before_action :authenticate_user!, except: %i[show followers followees]

  before_action :set_user

  before_action :set_from,             only: :show
  before_action :set_order,            only: :show

  def show
    @pictures = @user.pictures.order_by_time.page(params[:page])
    @pictures = @pictures.public_setting.enabled unless @user == current_user

    respond_with(@user) do |format|
      format.js { render template: "pictures/index" }
    end
  end

  def edit
  end

  def update
    @user.update(user_params)

    respond_with(@user)
  end

  def follow
    @user.followers << current_user
    respond_to do |format|
      format.html { redirect_back(fallback_location: @user) }
      format.json { head :no_content }
    end
  end

  def unfollow
    @user.followers.delete(current_user)
    respond_to do |format|
      format.html { redirect_back(fallback_location: @user) }
      format.json { head :no_content }
    end
  end

  def followers
    @followers = User.joins(:followee_relationships).
      where("follows.followee_id = ?", @user.id).
      order("follows.created_at DESC").
      page(1).per(100)
  end

  def followees
    @followees = User.joins(:follower_relationships).
      where("follows.follower_id = ?", @user.id).
      order("follows.created_at DESC").
      page(1).per(100)
  end

  private

  def set_user
    @user = User.find_by!(username: params[:username])
  end

  def user_params
    params.require(:user).permit(:fullname, :avatar, :description)
  end
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <h4 class="alert-heading"><%= form_errors_heading(@user) %></h4>

      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :fullname %>
    <%= f.text_field :fullname, autocomplete: 'name', maxlength: User::FULLNAME_LENGTH_MAX, class: "form-control #{'is-invalid' if @user.errors[:description].any?}" %>
  </div>

  <div class="form-group">
    <%= f.label :avatar %>
    <div class="custom-file">
      <%= f.file_field :avatar, class: 'custom-file-input', accept: 'image/jpeg' %>
      <label class="custom-file-label" for="user_avatar">Choose file...</label>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, placeholder: 'Add a description to your profile', rows: 3, maxlength: User::DESCRIPTION_LENGTH_MAX, class: "form-control #{'is-invalid' if @user.errors[:description].any?}" %>
  </div>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/users/_header.html.erb
<div class="btn-group float-right" role="group" style="position:absolute;right:15px;z-index:1">
  <% if current_user == @user %>
    <%= link_to edit_user_path(@user), class: 'btn btn-outline-primary', role: 'button' do %>
      <%= fa_icon("pencil") %> Edit profile
    <% end %>
  <% elsif @user.followers.include?(current_user) %>
    <%= link_to "Unfollow", unfollow_user_path(@user), method: :put, class: 'btn btn-outline-primary', role: 'button' %>
  <% else %>
    <%= link_to "Follow", follow_user_path(@user), method: :put, class: 'btn btn-outline-primary', role: 'button' %>
  <% end %>
</div>

<div class="row align-items-center">
  <div class="col col-sm-auto text-sm-left text-center mb-3 mb-sm-0">
    <% if @user.avatar? %>
      <%= image_tag(@user.avatar.thumb_url('100x100'), alt: 'avatar', class: 'rounded-circle', width: 100, height: 100) %>
    <% else %>
      <span class="rounded-circle align-bottom d-inline-block text-white" style="background:#ccc;width:100px;height:100px">
        <i class="fa fa-user-o align-top text-center" style="width:100px;line-height:95px;font-size:70px" aria-hidden="true"></i>
      </span>
    <% end %>
  </div>
  <div class="col-sm text-sm-left text-center">
    <h1 class="mb-0 overflow-hidden">
      <%= @user.name %>
    </h1>
  </div>
</div>

<hr class="mt-4 mb-4">

<ul class="nav nav-pills">
  <li class="nav-item">
    <%= link_to t('profile'), @user, class: "nav-link#{body_class == 'users-show' ? ' active' : ''}" %>
  </li>
  <li class="nav-item">
    <%= link_to t('picture', count: @user.pictures.public_setting.enabled.count), user_pictures_path(@user), class: "nav-link#{body_class == 'pictures-index' ? ' active' : ''}" %>
  </li>
  <li class="nav-item">
    <%= link_to t('album', count: @user.albums.count), user_albums_path(@user), class: "nav-link#{body_class == 'albums-index' ? ' active' : ''}" %>
  </li>
  <li class="nav-item">
    <%= link_to t('followee', count: @user.followees.count), followees_user_path(@user), class: "nav-link#{body_class == 'users-followees' ? ' active' : ''}" %>
  </li>
  <li class="nav-item">
    <%= link_to t('follower', count: @user.followers.count), followers_user_path(@user), class: "nav-link#{body_class == 'users-followers' ? ' active' : ''}" %>
  </li>
</ul>

app/views/users/_user_card.html.erb
<div class="card mb-3">
  <div class="card-body py-2 px-3">
    <div class="row align-items-center">
      <div class="col-auto">
        <%= link_to(user) do %>
          <% if user.avatar? %>
            <%= image_tag(user.avatar.thumb_url('100x100'), alt: 'avatar', class: 'rounded-circle', width: 50, height: 50) %>
          <% else %>
            <span class="rounded-circle align-bottom d-inline-block text-white" style="background:#ccc;width:50px;height:50px">
              <i class="fa fa-user-o align-top text-center" style="width:50px;line-height:45px;font-size:30px" aria-hidden="true"></i>
            </span>
          <% end %>
        <% end %>
      </div>
      <div class="col text-truncate px-0">
        <%= link_to(user.name, user, class: 'text-dark') %>
      </div>
      <div class="col-auto">
        <% if user == current_user || user.followers.include?(current_user) %>
          <%= link_to 'Follow', '#', class: 'btn btn-outline-primary disabled', role: 'button' %>
        <% else %>
          <%= link_to 'Follow', follow_user_path(user), method: :put, class: 'btn btn-outline-primary', role: 'button' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="row">
  <div class="col-lg-3">
    <%= render 'account/nav' %>
  </div>
  <div class="col-lg-6">
    <div class="card">
      <div class="card-header text-muted"><%= title 'Edit profile' %></div>
      <div class="card-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/users/followees.html.erb
<% title "#{@user.name} followees" %>

<%= render 'users/header' %>

<div class="row mt-4">
  <% @followees.each do |followee| %>
    <div class="col-md-6">
      <%= render 'user_card', user: followee %>
    </div>
  <% end %>
</div>

app/views/users/followers.html.erb
<% title "#{@user.name} followers" %>

<%= render 'users/header' %>

<div class="row mt-4">
  <% @followers.each do |follower| %>
    <div class="col-md-6">
      <%= render 'user_card', user: follower %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<% title "Pictures by #{@user.name}" %>
<% set_meta_tags og: { image: @user.avatar.thumb_url('100x100'), type: 'profile', profile: { username: @user.username } } %>

<%= render 'header' %>

<div class="row mt-4">
  <div class="col-sm">
    <table class="table">
      <tr>
        <th scope="row">Joined</th>
        <td><%= timeago_tag @user.created_at %></td>
      </tr>

      <tr>
        <th scope="row">Views</th>
        <td><%= @user.pictures.sum(:views_count) %></td>
      </tr>

      <tr>
        <th scope="row">Likes</th>
        <td><%= @user.pictures.sum(:cached_votes_total) %></td>
      </tr>
    </table>
  </div>

  <div class="col-sm">
    <%= simple_format(@user.description, class: 'overflow-hidden') %>
  </div>
</div>

<div class="mt-5">
  <h3>Most popular pictures</h3>

  <%= render 'pictures/gallery', pictures: @user.pictures.public_setting.enabled.order_by_view.page(1).per(6) %>
</div>