config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: "account", path_names: {
    sign_up: "signup",
    sign_in: "signin",
    sign_out: "signout"
  }

  namespace :account do
    get "/", to: redirect("/account/settings/edit")
    get "/settings", to: redirect("/account/settings/edit")
    resource :settings, only: %i[edit update]
    resource :billing, only: :show
    resources :charges, only: :create
  end

  resources :pictures, param: :token, path: "p" do
    resource :lightbox, only: %i[show], module: :pictures
    resource :disabled, only: %i[create destroy], module: :pictures
    resource :featured, only: %i[create destroy], module: :pictures
    resource :like, only: %i[create destroy], module: :pictures

    collection do
      get "import"
      get "search"
    end
  end

  get "/u", to: redirect("/explore")
  resources :users, param: :username, path: "u", only: %i[show edit update] do
    member do
      put "follow"
      put "unfollow"
      get "followers"
      get "followees"
    end

    resources :albums, only: :index
    resources :pictures, only: :index
  end

  get "/a", to: redirect("/explore")
  resources :albums, param: :token, except: :index, path: "a" do
    resources :pictures, only: :index
  end

  namespace :admin do
    get "/", to: redirect("/admin/users")
    resources :billings, only: :index
    resources :users, only: :index
    resources :pictures, only: :index
    resources :invitations, param: :token, only: :index do
      member do
        put "approve"
      end
    end
  end

  resources :invitations, only: %i[new create]

  get "explore" => "explore#index"
  get "contact" => "about#contact"
  get "pricing" => "about#pricing"
  get "privacy" => "about#privacy"
  get "terms" => "about#terms"
  get "rules" => "about#rules"

  devise_scope :user do
    authenticated :user do
      root "timeline#index", as: :authenticated_root
    end

    unauthenticated do
      root "welcome#index"
    end
  end
end

app/models/picture.rb
# == Schema Information
#
# Table name: pictures
#
#  id                 :integer          not null, primary key
#  description        :text
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  user_id            :integer
#  token              :string
#  views_count        :integer          default(0), not null
#  image_height       :integer
#  image_width        :integer
#  is_featured        :boolean          default(FALSE), not null
#  image              :integer          not null
#  image_filename     :string
#  privacy_setting    :integer          default("public")
#  cached_votes_total :integer          default(0)
#  status             :integer          default("enabled")
#

require "exifr/jpeg"

class Picture < ApplicationRecord
  include OrderQuery
  include Tokenizable

  CAPTION_LENGTH_MAX = 500

  attr_accessor :protected_param, :regenerate_secret

  belongs_to :user
  has_and_belongs_to_many :albums, after_add: :touch_album, after_remove: :touch_album

  mount_uploader :image, ImageUploader

  acts_as_votable

  order_query :order_by_view, %i[views_count desc]
  order_query :order_by_time, %i[created_at desc]

  enum privacy_setting: %i[public protected private], _suffix: :setting
  enum status: %i[enabled disabled]

  validates_presence_of :image
  validates :description, length: { maximum: CAPTION_LENGTH_MAX }
  validate :user_balance_cannot_be_negative, on: :create if Rails.configuration.payment_enabled

  after_create_commit :notify!
  before_update :regenerate_protected_secret!, if: :regenerate_secret

  def initialize(params = {})
    super
    write_attribute(:privacy_setting, params[:privacy_setting] || user.default_privacy_setting) if user.present?
  end

  def notify!
    PictureNotificationJob.perform_later(self)
  end

  def alt
    description.presence || "Picture #{token}"
  end

  def exif
    # TODO: Save in database
    @exif ||= EXIFR::JPEG.new(StringIO.new(image.file.read))
  end

  def protected_secret
    Digest::SHA1.hexdigest(image.filename) if protected_setting?
  end

  def regenerate_protected_secret!
    Digest::SHA1.hexdigest(image.generate_filename) if protected_setting?
  end

  def self.featured
    where(is_featured: true)
  end

  private

  def touch_album(album)
    album.touch if persisted?
  end

  def user_balance_cannot_be_negative
    errors.add(:user_id, "data balance cannot be negative") if user.balance.negative?
  end
end

app/controllers/admin/pictures_controller.rb
class Admin::PicturesController < Admin::AdminController
  def index
    @pictures = Picture.disabled.order_by_time
  end
end

app/controllers/pictures/disableds_controller.rb
class Pictures::DisabledsController < Admin::AdminController
  before_action :set_picture

  def create
    @picture.update(status: "disabled")
    respond_with(@picture, flash: false)
  end

  def destroy
    @picture.update(status: "enabled")
    respond_with(@picture, flash: false)
  end

  private

  def set_picture
    @picture = Picture.find_by!(token: params[:picture_token])
  end
end

app/controllers/pictures/featureds_controller.rb
class Pictures::FeaturedsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_picture

  def create
    authorize(@picture, "feature?")
    @picture.update(is_featured: true)
    respond_with(@picture, flash: false)
  end

  def destroy
    authorize(@picture, "unfeature?")
    @picture.update(is_featured: false)
    respond_with(@picture, flash: false)
  end

  private

  def set_picture
    @picture = Picture.find_by!(token: params[:picture_token])
  end
end

app/controllers/pictures/lightboxes_controller.rb
class Pictures::LightboxesController < PicturesController
  private

  def set_picture
    @picture = Picture.find_by!(token: params[:picture_token])
  end
end

app/controllers/pictures/likes_controller.rb
class Pictures::LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_picture

  def create
    @picture.liked_by(current_user)
    respond_with(@picture, flash: false)
  end

  def destroy
    @picture.unliked_by(current_user)
    respond_with(@picture, flash: false)
  end

  private

  def set_picture
    @picture = Picture.find_by!(token: params[:picture_token])
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  include PaginationContext

  before_action :authenticate_user!, except: %i[index search show]

  before_action :set_picture,        except: %i[index import search new create]
  before_action :set_album,            only: %i[index show]
  before_action :set_user,             only: %i[index show]

  before_action :set_from,             only: %i[index show]
  before_action :set_order,            only: %i[index show]

  before_action :set_pictures,         only: %i[index show]

  def index
    case @order
    when "view"
      @pictures = @pictures.order_by_view.page(params[:page])
    when "time"
      @pictures = @pictures.order_by_time.page(params[:page])
    else
      raise ActionController::BadRequest, "Invalid query parameters: order"
    end
  end

  def search
    if params[:q].present?
      @pictures = Picture.public_setting.enabled.
        where("description ILIKE ?", "%#{params[:q]}%").page(params[:page])
    end

    respond_to do |format|
      format.html # search.html.erb
      format.js { render template: "pictures/index" }
    end
  end

  def import
  end

  def show
    @picture.protected_param = params[:secret]
    authorize @picture

    case @order
    when "view"
      @previous_picture = @pictures.order_by_view_at(@picture).previous(false)
      @next_picture     = @pictures.order_by_view_at(@picture).next(false)
    else
      @previous_picture = @pictures.order_by_time_at(@picture).previous(false)
      @next_picture     = @pictures.order_by_time_at(@picture).next(false)
    end

    Picture.increment_counter(:views_count, @picture.id)
  end

  def new
    @picture = current_user.pictures.new
  end

  def edit
  end

  def create
    @picture = current_user.pictures.create(picture_params)
    respond_with(@picture)
  end

  def update
    @picture.update(picture_params)
    respond_with(@picture)
  end

  def destroy
    @picture.destroy
    respond_with(@picture)
  end

  protected

  def set_picture
    @picture = Picture.find_by!(token: params[:token])
  end

  def set_album
    token = params[:album_token] || params[:from] unless %w[all explore user].include?(params[:from])

    @album = Album.find_by(token: token) if token
  end

  def set_user
    @user =
      if params[:user_username]
        User.find_by!(username: params[:user_username])
      elsif @picture
        @picture.user
      end
  end

  def set_pictures
    @pictures =
      case @from
      when "all"
        Picture.public_setting.enabled
      when "explore"
        Picture.featured.public_setting.enabled
      when "user"
        if @user == current_user
          @user.pictures
        else
          @user.pictures.public_setting.enabled
        end
      when /\w+/ # album token
        raise(ActionController::BadRequest, "Invalid query parameters: from") if @album.nil?

        if @album.user == current_user
          @album.pictures
        else
          @album.pictures.public_setting.enabled
        end
      end
  end

  def picture_params
    params.require(:picture).permit(:description, :image, :privacy_setting, :regenerate_secret, album_ids: [])
  end
end

app/helpers/picture_helper.rb
module PictureHelper
  def picture_description_format(description, options = {})
    if options[:truncate]
      description = truncate(description, length: options[:truncate], separator: ".")
      options.delete(:truncate)
    end

    simple_format(description, options).
      gsub(/(#\w+)/) { |tag| link_to(tag, search_pictures_path(q: tag)) }.
      html_safe
  end
end

app/views/pictures/_form.html.erb
<%= form_for(picture) do |f| %>
  <% if picture.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <h4 class="alert-heading"><%= form_errors_heading(picture) %></h4>

      <ul>
        <% picture.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% unless picture.persisted? %>
    <div class="form-group">
      <%= f.label :image %>
      <div class="custom-file">
        <%= f.file_field :image, class: 'custom-file-input', accept: 'image/jpeg' %>
        <label class="custom-file-label" for="picture_image">Choose file...</label>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, placeholder: 'Add a description to your picture', rows: 3, maxlength: Picture::CAPTION_LENGTH_MAX, class: "form-control #{"is-invalid" if picture.errors[:description].any?}" %>
  </div>

  <div class="form-group">
    <%= f.label :album_ids, 'Albums' %>
    <%= f.collection_select :album_ids, current_user.albums, :id, :title, { selected: picture.album_ids }, { class: 'form-control', multiple: true } %>
  </div>

  <div class="form-group">
    <%= f.label :privacy_setting %>
    <%= f.select :privacy_setting, Picture.privacy_settings.keys.to_a, {}, { class: 'custom-select' } %>
  </div>

  <% if picture.persisted? %>
    <div class="form-check form-group <%= 'd-none' unless picture.protected_setting? %>">
      <%= f.check_box :regenerate_secret, class: 'form-check-input' %>
      <%= f.label :regenerate_secret, class: 'form-check-label' %>
    </div>
  <% end %>

  <div class="">
    <% if picture.persisted? %>
      <%= link_to 'Delete', picture, method: :delete, data: { confirm: 'This picture will be deleted, are you sure?' }, class: 'btn btn-link text-danger pull-right', role: 'button' %>
    <% else %>
      <%= link_to t('.upload_many_pictures'), import_pictures_path, class: 'btn btn-link pull-right px-0', role: 'button' %>
    <% end %>

    <%= f.submit class: 'btn btn-primary', disabled: picture.new_record? && current_user.balance.negative? %>
  </div>
<% end %>

app/views/pictures/_gallery.html.erb
<% if pictures %>
  <div id="gallery" class="justified-gallery mt-3">
    <%= render 'pictures/pictures', pictures: pictures %>
  </div>

  <p class="next-page text-center mt-3">
    <%= link_to_next_page pictures, t('pictures.gallery.load_more'), remote: true, class: 'btn btn-outline-secondary', role: 'button' %>
  </p>
<% end %>

app/views/pictures/_pictures.html.erb
<% pictures.each do |picture| %>
  <%= link_to picture_path(picture, from: @from, order: @order) do %>
    <%= image_tag(picture.image.thumb_url('x300'), alt: picture.alt, size: picture.image.thumb_size('x300')) %>
  <% end %>
<% end %>

app/views/pictures/_share_modal.html.erb
<div class="modal fade" id="shareModal" tabindex="-1" role="dialog" aria-labelledby="shareModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="shareModalLabel">Share picture</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <% if @picture.protected_setting? %>
          <div class="alert alert-warning" role="alert">
            <%= fa_icon "lock", class: "mr-1" %>
            This URL is protected by a secret.
            <% if current_user == @picture.user %>
              <%= link_to "Edit the picture", edit_picture_path(@picture), class: "alert-link" %> to make it public
              or change the secret.
            <% else %>
              <%= link_to "Ask the author", @picture.user, class: "alert-link" %> for permission before sharing it.
            <% end %>
          </div>
        <% end %>

        <div id="share-url-group" class="form-group">
          <label for="share-url">URL to share</label>
          <input type="url" class="form-control" id="share-url" placeholder="URL" value="<%= picture_url(@picture, secret: @picture.protected_secret) %>" readonly>
        </div>

        <% if @picture.public_setting? %>
          <a href="http://twitter.com/share?url=<%=u picture_url(@picture) %>&text=<%=u truncate(@picture.description, length: 100, separator: '.') %>" target="_blank" class="btn" role="button" style="width:3rem;color:white;background:#4099FF">
            <%= fa_icon("twitter") %>
          </a>
          <a href="https://www.facebook.com/sharer/sharer.php?u=<%=u picture_url(@picture) %>" target="_blank" class="btn" role="button" style="width:3rem;color:white;background:#3B5998">
            <%= fa_icon("facebook") %>
          </a>
          <a href="https://plus.google.com/share?url=<%=u picture_url(@picture) %>" target="_blank" class="btn" role="button" style="width:3rem;color:white;background:#EA4335">
            <%= fa_icon("google") %>
          </a>

          <% if user_signed_in? && current_user.admin? %>
            <% if @picture.is_featured %>
              <%= link_to picture_featured_path(@picture), method: :delete, class: 'btn btn-outline-primary', role: 'button' do %>
                <%= fa_icon("check") %> Unfeature in Explore
              <% end %>
            <% else %>
              <%= link_to picture_featured_path(@picture), method: :post, class: 'btn btn-outline-primary', role: 'button' do %>
                <%= fa_icon("check") %> Feature in Explore
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Close</button>
        <button id="share-url-button" type="button" class="btn btn-primary">Copy to clipboard</button>
      </div>
    </div>
  </div>
</div>
<script>
  $('#share-url-button').on('click', function() {
    $('#share-url').select();
    if (document.execCommand("copy")) {
      $('#share-url').addClass('form-control-success');
      $('#share-url-group').addClass('has-success');
    } else {
      $('#share-url').addClass('form-control-danger');
      $('#share-url-group').addClass('has-danger');
    }
  })
</script>

app/views/pictures/_user.html.erb
<div class="row flex-nowrap" style="height:50px">
  <div class="col-auto">
    <%= link_to(picture.user) do %>
      <% if picture.user.avatar? %>
        <%= image_tag(picture.user.avatar.thumb_url('100x100'), alt: 'avatar', class: 'rounded-circle', width: 50, height: 50) %>
      <% else %>
        <span class="rounded-circle align-bottom d-inline-block text-white" style="background:#ccc;width:50px;height:50px">
          <i class="fa fa-user-o align-top text-center" style="width:50px;line-height:45px;font-size:30px" aria-hidden="true"></i>
        </span>
      <% end %>
    <% end %>
  </div>
  <div class="col pl-0 text-truncate">
    <%= link_to(picture.user, class: 'overflow-hidden') do %>
      <div style="line-height:25px" class="text-truncate">
        <%= picture.user.name %>
      </div>
    <% end %>
    <div style="line-height:25px" class="text-muted text-truncate">
      <% if picture.user == current_user || picture.protected_setting? %>
        <span class="float-right" data-toggle="tooltip" data-placement="left" title="<%= picture.privacy_setting %>">
          <% if picture.public_setting? %>
            <%= fa_icon "globe" %>
          <% elsif picture.protected_setting? %>
            <%= fa_icon "lock" %>
          <% else %>
            <%= fa_icon "minus-circle" %>
          <% end %>
        </span>
      <% end %>
      <%= timeago_tag picture.created_at %>
    </div>
  </div>
</div>

app/views/pictures/edit.html.erb
<div class="row justify-content-center">
  <div class="col-lg-6">
    <div class="card">
      <div class="card-header text-muted"><%= title 'Edit picture' %></div>
      <div class="card-body">
        <%= image_tag(@picture.image.thumb_url('500x500'), class: 'img-fluid mb-3') %>

        <%= render 'form', picture: @picture %>
      </div>
    </div>
  </div>
</div>

app/views/pictures/import.html.erb
<div class="row justify-content-center">
  <div class="col-lg-6">
    <div class="card">
      <div class="card-header text-muted"><%= title t('pictures.form.upload_many_pictures') %></div>
      <div class="card-body">
        <% unless policy(Picture).upload? %>
          <div class="alert alert-danger" role="alert">
            <strong>Warning!</strong>
            Your data balance is <strong>-<%= number_to_human_size(-current_user.balance) %></strong>,
            you need to <%= link_to 'top up', account_billing_path, class: 'alert-link' %> before uploading
            new pictures.
          </div>
        <% end %>

        <%= form_for(Picture.new, html: { class: "custom-dropzone d-flex flex-wrap border-primary bg-light", style: "border:dashed 2px" }) do |f| %>
          <div class="text-center text-primary my-4 dz-message d-flex flex-column align-items-center justify-content-center">
            <div><%= fa_icon("cloud-upload 3x") %></div>
            <div>Drop files here to upload</div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pictures/index.html.erb
<% if @user %>
  <div class="mb-4">
    <%= render 'users/header' %>
  </div>
<% end %>

<%= render 'pictures/gallery', pictures: @pictures %>

app/views/pictures/index.js.erb
$('body').addClass('infinite-scrolling');

// Append new data
$("<%=j render(:partial => 'pictures/pictures', :object => @pictures) %>")
  .appendTo($('#gallery'));

// Reload gallery script
$('#gallery').justifiedGallery('norewind');

// Update next-page link
<% if @pictures.last_page? %>
  $('.next-page').html('');
  $('body').removeClass('infinite-scrolling');
<% else %>
  $('.next-page').html("<%=j link_to_next_page @pictures, t('pictures.gallery.load_more'), remote: true, class: 'btn btn-outline-secondary infinite-scrolling', role: 'button' %>");
<% end %>

app/views/pictures/lightbox.html.erb
<% content_for(:title, "#{truncate(@picture.caption.presence || 'Picture', length: 100, separator: '.')} by #{@picture.user.name} (#{@picture.token}) - Lightbox") %>

<div class="row align-items-center" style="height:100vh">
  <div class="col-1 p-0 text-center">
    <% if @previous_picture %>
      <%= link_to lightbox_picture_path(@previous_picture, from: @from, order: @order), class: '', aria_label: 'previous' do %>
        <%= fa_icon("chevron-left") %>
        <span class="sr-only">Previous</span>
      <% end %>
    <% end %>
  </div>

  <div class="col-10 p-0 text-center">
    <%= link_to(picture_path(@picture, secret: @picture.protected_secret, from: @from, order: @order), style: 'cursor:zoom-out') do %>
      <%= image_tag(@picture.image_url, alt: @picture.alt, class: 'img-fluid mx-auto d-block', style: 'max-height:90vh') %>
    <% end %>
  </div>

  <div class="col-1 p-0 text-center">
    <% if @next_picture %>
      <%= link_to lightbox_picture_path(@next_picture, from: @from, order: @order), class: '', aria_label: 'next' do %>
        <%= fa_icon("chevron-right") %>
        <span class="sr-only">Next</span>
      <% end %>
    <% end %>
  </div>
</div>

app/views/pictures/new.html.erb
<div class="row justify-content-center">
  <div class="col-lg-6">
    <div class="card">
      <div class="card-header text-muted"><%= title t('pictures.form.upload_a_picture') %></div>
      <div class="card-body">
        <% unless policy(Picture).upload? %>
          <div class="alert alert-danger" role="alert">
            <strong>Warning!</strong>
            Your data balance is <strong>-<%= number_to_human_size(-current_user.balance) %></strong>,
            you need to <%= link_to 'top up', account_billing_path, class: 'alert-link' %> before uploading
            new pictures.
          </div>
        <% end %>
        <%= render 'form', picture: @picture %>
      </div>
    </div>
  </div>
</div>

app/views/pictures/search.html.erb
<h1 class="mb-4">Search pictures</h1>

<%= render 'layouts/search' %>

<% if params[:q].present? %>
  <% title "Pictures about '#{params[:q]}'" %>

  <p class="mt-4"><%= t('picture', count: @pictures.total_count) %> found</p>

  <%= render 'pictures/gallery', pictures: @pictures %>
<% else %>
  <% title 'Search' %>
<% end %>

app/views/pictures/show.html.erb
<% title "#{truncate((@picture.description.presence || 'Picture').lines.first.chomp, length: 60, separator: '.')} by #{@picture.user.name} (#{@picture.token})" %>
<% set_meta_tags og: { image: @picture.image.thumb_url('800x800') } %>
<% set_meta_tags twitter: { card: 'photo', image: @picture.image.thumb_url('800x800') } %>

<% if @picture.disabled? %>
  <div class="alert alert-danger" role="alert"><%= t('.disabled') %></div>
<% end %>

<div class="row" style="position:relative">
  <div class="col-md-8">
    <nav aria-label="picture pagination">
      <ul class="pagination pagination justify-content-center">
        <% if @previous_picture %>
          <li class="page-item">
            <% set_meta_tags prev: picture_url(@previous_picture) %>
            <%= link_to picture_path(@previous_picture, from: @from, order: @order), id: 'previous', class: 'page-link', aria_label: 'previous' do %>
              <%= fa_icon("chevron-left") %>
              <span class="sr-only">Previous</span>
            <% end %>
          </li>
        <% else %>
          <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1" aria-label="previous">
              <%= fa_icon("chevron-left") %>
              <span class="sr-only">Previous</span>
            </a>
          </li>
        <% end %>
        <% if @next_picture %>
          <li class="page-item">
            <% set_meta_tags next: picture_url(@next_picture) %>
            <%= link_to picture_path(@next_picture, from: @from, order: @order), id: 'next', class: 'page-link', aria_label: 'next' do %>
              <%= fa_icon("chevron-right") %>
              <span class="sr-only">Next</span>
            <% end %>
          </li>
        <% else %>
          <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1" aria-label="next">
              <%= fa_icon("chevron-right") %>
              <span class="sr-only">Next</span>
            </a>
          </li>
        <% end %>
      </ul>
    </nav>
  </div>
  <div class="mr-3" style="position:absolute;right:0">
    <% if user_signed_in? %>
      <span class="d-none d-sm-inline">
      <% if current_user.admin? %>
        <% if @picture.disabled? %>
          <%= link_to picture_disabled_path(@picture), method: :delete, class: 'btn btn-outline-danger', role: 'button' do %>
            <%= fa_icon("ban") %> Enable
          <% end %>
        <% else %>
          <%= link_to picture_disabled_path(@picture), method: :post, class: 'btn btn-outline-danger', role: 'button' do %>
            <%= fa_icon("ban") %> Disable
          <% end %>
        <% end %>
      <% end %>
      </span>

      <% if @picture.user == current_user %>
        <%= link_to edit_picture_path(@picture), class: 'btn btn-outline-primary ml-1', role: 'button' do %>
          <%= fa_icon("pencil") %> Edit
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-md-8">
    <%= link_to(picture_lightbox_path(@picture, secret: @picture.protected_secret, from: @from, order: @order), style: 'cursor:zoom-in') do %>
      <%= image_tag(@picture.image.thumb_url('800x800'), alt: @picture.alt, class: 'img-fluid mx-auto d-block', style: 'max-height:75vh') %>
    <% end %>
  </div>

  <div class="col-md-4 d-flex flex-column mt-3 mt-md-0">
    <div>
      <div class="mb-3"><%= render 'pictures/user', picture: @picture %></div>

      <% if @picture.description.present? %>
        <%= picture_description_format(@picture.description) %>
      <% end %>
    </div>

    <div class="mt-auto">
      <p>
        <%= t('.license') %>:
        <a href="http://creativecommons.org/licenses/<%= @picture.user.default_license.sub('CC ', '').downcase %>/4.0/">
          <%= @picture.user.default_license %>
        </a>
      </p>

      <hr>

      <p>
        <%= t('view', count: @picture.views_count) %>,
        <%= t('like', count: @picture.cached_votes_total) %>
      </p>

      <div class="btn-toolbar" role="toolbar" aria-label="Picture social toolbar">
        <div class="btn-group mr-2" role="group">
          <% if user_signed_in? && current_user.liked?(@picture) %>
            <%= link_to picture_like_path(@picture), method: :delete, class: 'btn btn-outline-secondary', role: 'button' do %>
              <%= fa_icon("heart") %> Unlike
            <% end %>
          <% else %>
            <%= link_to picture_like_path(@picture), method: :post, class: 'btn btn-outline-secondary', role: 'button' do %>
              <%= fa_icon("heart") %> Like
            <% end %>
          <% end %>
        </div>

        <div class="btn-group" role="group">
          <button type="button" class="btn btn-outline-secondary" data-toggle="modal" data-target="#shareModal"<%= @picture.private_setting? ? "disabled" : "" %>>
            <%= fa_icon("share") %> Share
          </button>
        </div>
      </div>
    </div>
  </div>
</div>

<% if @picture.exif.exif? %>
  <div class="mt-5">
    <h3>Informations</h3>

    <table class="table">
      <% if @picture.exif.date_time %>
        <tr>
          <th scope="row">Date</th>
          <td><%= @picture.exif.date_time.strftime('%F %T') %></td>
        </tr>
      <% end %>

      <% if @picture.exif.model %>
        <tr>
          <th scope="row">Camera</th>
          <td><%= @picture.exif.model %></td>
        </tr>
      <% end %>

      <% if @picture.exif.focal_length %>
        <tr>
          <th scope="row">Focal Length</th>
          <td><%= @picture.exif.focal_length.to_f %> mm</td>
        </tr>
      <% end %>

      <% if @picture.exif.f_number %>
        <tr>
          <th scope="row">Apperture</th>
          <td>f/<%= @picture.exif.f_number.to_f %></td>
        </tr>
      <% end %>

      <% if @picture.exif.exposure_time %>
        <tr>
          <th scope="row">Exposure Time</th>
          <td><%= @picture.exif.exposure_time.to_s.sub(/\/1$/, '') %> s</td>
        </tr>
      <% end %>

      <% if @picture.exif.iso_speed_ratings %>
        <tr>
          <th scope="row">ISO</th>
          <td><%= @picture.exif.iso_speed_ratings %></td>
        </tr>
      <% end %>
    </table>
  </div>
<% end %>

<% unless @picture.albums.empty? %>
  <div class="mt-5">
    <h3>Albums</h3>

    <%= render 'albums/albums', albums: @picture.albums.order_by_time %>
  </div>
<% end %>

<%= render partial: 'share_modal' %>