config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: "account", path_names: {
    sign_up: "signup",
    sign_in: "signin",
    sign_out: "signout"
  }

  namespace :account do
    get "/", to: redirect("/account/settings/edit")
    get "/settings", to: redirect("/account/settings/edit")
    resource :settings, only: %i[edit update]
    resource :billing, only: :show
    resources :charges, only: :create
  end

  resources :pictures, param: :token, path: "p" do
    resource :lightbox, only: %i[show], module: :pictures
    resource :disabled, only: %i[create destroy], module: :pictures
    resource :featured, only: %i[create destroy], module: :pictures
    resource :like, only: %i[create destroy], module: :pictures

    collection do
      get "import"
      get "search"
    end
  end

  get "/u", to: redirect("/explore")
  resources :users, param: :username, path: "u", only: %i[show edit update] do
    member do
      put "follow"
      put "unfollow"
      get "followers"
      get "followees"
    end

    resources :albums, only: :index
    resources :pictures, only: :index
  end

  get "/a", to: redirect("/explore")
  resources :albums, param: :token, except: :index, path: "a" do
    resources :pictures, only: :index
  end

  namespace :admin do
    get "/", to: redirect("/admin/users")
    resources :billings, only: :index
    resources :users, only: :index
    resources :pictures, only: :index
    resources :invitations, param: :token, only: :index do
      member do
        put "approve"
      end
    end
  end

  resources :invitations, only: %i[new create]

  get "explore" => "explore#index"
  get "contact" => "about#contact"
  get "pricing" => "about#pricing"
  get "privacy" => "about#privacy"
  get "terms" => "about#terms"
  get "rules" => "about#rules"

  devise_scope :user do
    authenticated :user do
      root "timeline#index", as: :authenticated_root
    end

    unauthenticated do
      root "welcome#index"
    end
  end
end

app/controllers/about_controller.rb
require "mail"

class AboutController < ApplicationController
  def contact
    @email = Mail::Address.new(ENV["MAILER_SENDER"]).address
  end

  def pricing
  end

  def privacy
  end

  def terms
  end

  def rules
  end
end

app/views/about/_nav.html.erb
<ul class="nav nav-pills flex-column mb-3">
  <li class="nav-item">
    <%= link_to t('contact.title'), contact_path, class: "nav-link #{'active' if body_class == 'about-contact'}" %>
  </li>
  <li class="nav-item">
    <%= link_to t('rules.title'), rules_path, class: "nav-link #{'active' if body_class == 'about-rules'}" %>
  </li>
  <li class="nav-item">
    <%= link_to t('terms.title'), terms_path, class: "nav-link #{'active' if body_class == 'about-terms'}" %>
  </li>
  <li class="nav-item">
    <%= link_to t('privacy.title'), privacy_path, class: "nav-link #{'active' if body_class == 'about-privacy'}" %>
  </li>
  <% if Rails.configuration.payment_enabled %>
    <li class="nav-item">
      <%= link_to t('pricing.title'), pricing_path, class: "nav-link #{'active' if body_class == 'about-pricing'}" %>
    </li>
  <% end %>
</ul>

app/views/about/contact.html.erb
<% title t('contact.title') %>

<div class="row">
  <div class="col-lg-3">
    <%= render 'about/nav' %>
  </div>
  <div class="col-lg-6">
    <div class="card">
      <div class="card-header text-muted"><%= t('contact.title') %></div>
      <div class="card-body">
        <%= render_markdown(t('contact.body_markdown', email: email_munging(@email))) %>
      </div>
    </div>
  </div>
</div>

app/views/about/pricing.html.erb
<% title t('pricing.title') %>

<div class="row">
  <div class="col-lg-3">
    <%= render 'about/nav' %>
  </div>
  <div class="col-lg-6">
    <div class="card">
      <div class="card-header text-muted"><%= t('pricing.title') %></div>
      <div class="card-body">
        <%= t('pricing.body_html', cost_per_gigabyte: cost_per_gigabyte, price_per_gigabyte: price_per_gigabyte) %>

        <% unless user_signed_in? %>
          <p class="text-center mt-5"><%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-lg btn-primary', role: 'button' %></p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/about/privacy.html.erb
<% title t('privacy.title') %>

<div class="row">
  <div class="col-lg-3">
    <%= render 'about/nav' %>
  </div>
  <div class="col-lg-6">
    <div class="card">
      <div class="card-header text-muted"><%= t('privacy.title') %></div>
      <div class="card-body">
        <%= render_markdown(t('privacy.body_markdown', payment_information: Rails.configuration.payment_enabled ? t('privacy.payment_information_markdown') : '')) %>
      </div>
    </div>
  </div>
</div>

app/views/about/rules.html.erb
<% title t('rules.title') %>

<div class="row">
  <div class="col-lg-3">
    <%= render 'about/nav' %>
  </div>
  <div class="col-lg-6">
    <div class="card">
      <div class="card-header text-muted"><%= t('rules.title') %></div>
      <div class="card-body">
        <%= render_markdown(t('rules.body_markdown')) %>
      </div>
    </div>
  </div>
</div>

app/views/about/terms.html.erb
<% title t('terms.title') %>

<div class="row">
  <div class="col-lg-3">
    <%= render 'about/nav' %>
  </div>
  <div class="col-lg-6">
    <div class="card">
      <div class="card-header text-muted"><%= t('terms.title') %></div>
      <div class="card-body">
        <%= render_markdown(t('terms.body_markdown')) %>
      </div>
    </div>
  </div>
</div>